### ISSUE TITLE
Enable Capture Assistant unit tests when moving to SDK 1.8.0

### ISSUE THREAD

**Issue by apartridge** [zivid/zivid-ros#10]
(Note: Capture Assistant not yet merged into master)

FileCamera does not support CA in SDK 1.7, so it cannot be used for unit tests. This is fixed in 1.8. Re-enable the relevant tests when we move  to SDK 1.8.0.

**Comment by runenordmo** [comment]
This one can be closed, @apartridge?

**Comment by apartridge** [comment]
The Capture Assistant unit tests are not enabled yet
