### ISSUE TITLE
Remove manual semanic version check

### ISSUE THREAD

**Issue by nedrebo** [zivid/zivid-ros#2]
From version 1.5.0 Zivid SDK implements the semantic version check correctly in CMake and the workaround below can be changed to passing the required version into find_package.

https://github.com/zivid/zivid-ros/blob/65504cfe89968d5b50638acf157ac94699203a3a/zivid_camera/CMakeLists.txt#L36

**Comment by apartridge** [comment]
This has now been fixed, in merge https://github.com/zivid/zivid-ros/commit/f7ca914d175781e714932773feb767e01c5f1b72
