### ISSUE TITLE
Exception: "Checksum in header does not match the checksum of the content"

### ISSUE THREAD

**Issue by dave992** [zivid/zivid-ros#53]
When reconnecting to the Zivid Camera (Zivid One+ M) I frequently get the following error:  
`Failed to initialize camera driver. Exception: "Checksum in header does not match the checksum of the content`

If this happens when using the ROS package, I also get this message in Zivid Studio when I try to reconnect there. 

The solution thus far has been, wait for ~30 seconds before trying again. Updating the SDK etc from v2.4.0 > v2.4.1 did not lead to a change in behavior. 

Previously I have been running the SDK v1.8, where I did not encounter this problem as far as I can remember. If it did happen, it was way less frequent. 

**System:**
Ubuntu 18.04 & ROS Melodic
Zivid One+ M
Zivid SDK v2.4.0 and v2.4.1
Zivid Studio v2.4.0 and v2.4.1
Zivid ROS: 9b85892cbe3099a436ab17d612940669b394170a

**Comment by SatjaSivcev** [comment]
Hi Dave, can you please email us at customersuccess@zivid.com and send us the log files. Instructions to get the log files can be found here: https://support.zivid.com/latest/troubleshooting.html
