### ISSUE TITLE
Add service to capture and save the frame 

### ISSUE THREAD

**Issue by torbsorb** [zivid/zivid-ros#67]
This service would wrap both the `capture()` API as well as `frame.save()`. It would take a path where the extension must match what `frame.save()` supports, see [Point Cloud formats](https://support.zivid.com/latest/reference-articles/point-cloud-structure-and-output-formats.html).
See also [Capture Tutorial - Save](https://support.zivid.com/latest/academy/camera/capture-tutorial.html#id2)

**Comment by apartridge** [comment]
This service was added in https://github.com/zivid/zivid-ros/commit/05964d6d57d1efcc2218424ae3b9da1ac6200ae0.
