### ISSUE TITLE
ros noetic catkin build error 

### ISSUE THREAD

**Issue by taisi5446** [zivid/zivid-ros#74]
I tried to build zivid-ros in noetic.

I was installed zivid core SDK with 4 deb files and all dependency of zivid-ros for rosdep. But catkin build faced some error like below.

How solve it?

When I build other packages, build successfully. Only zivid-ros has error like below.

erp42@erp42:~/catkin_ws$ catkin build zivid*
----------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/noetic
Workspace:                   /home/erp42/catkin_ws
----------------------------------------------------------
Build Space:        [exists] /home/erp42/catkin_ws/build
Devel Space:        [exists] /home/erp42/catkin_ws/devel
Install Space:      [unused] /home/erp42/catkin_ws/install
Log Space:          [exists] /home/erp42/catkin_ws/logs
Source Space:       [exists] /home/erp42/catkin_ws/src
DESTDIR:            [unused] None
----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
----------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
----------------------------------------------------------
Workspace configuration appears valid.
----------------------------------------------------------
[build] Found 25 packages in 0.0 seconds.                                      
[build] Package table is up to date.                                           
Starting  >>> zivid_camera                                                     
_______________________________________________________________________________
Errors     << zivid_camera:make /home/erp42/catkin_ws/logs/zivid_camera/build.make.003.log
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 136, in genmain
    pkg_map = get_pkg_map()
  File "/opt/ros/noetic/lib/python3/dist-packages/geneus/geneus_main.py", line 56, in get_pkg_map
    pkgs = packages.find_packages(ws)
  File "/usr/lib/python3/dist-packages/catkin_pkg/packages.py", line 103, in find_packages
    raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "actionlib":
- include/opt/ros/noetic/share/actionlib
- share/actionlib
Multiple packages found with the same name "actionlib_msgs":
- include/opt/ros/noetic/share/actionlib_msgs
- share/actionlib_msgs
Multiple packages found with the same name "actionlib_tutorials":
- include/opt/ros/noetic/share/actionlib_tutorials
- share/actionlib_tutorials
Multiple packages found with the same name "angles":
- include/opt/ros/noetic/share/angles
- share/angles
Multiple packages found with the same name "apriltag_ros":
- include/opt/ros/noetic/share/apriltag_ros
- share/apriltag_ros
Multiple packages found with the same name "bond":
- include/opt/ros/noetic/share/bond
- share/bond
Multiple packages found with the same name "bond_core":
- include/opt/ros/noetic/share/bond_core
- share/bond_core
Multiple packages found with the same name "bondcpp":
- include/opt/ros/noetic/share/bondcpp
- share/bondcpp
Multiple packages found with the same name "bondpy":
- include/opt/ros/noetic/share/bondpy
- share/bondpy
Multiple packages found with the same name "camera_calibration":
- include/opt/ros/noetic/share/camera_calibration
- share/camera_calibration
Multiple packages found with the same name "camera_calibration_parsers":
- include/opt/ros/noetic/share/camera_calibration_parsers
- share/camera_calibration_parsers
Multiple packages found with the same name "camera_info_manager":
- include/opt/ros/noetic/share/camera_info_manager
- share/camera_info_manager
Multiple packages found with the same name "catkin":
- include/opt/ros/noetic/share/catkin
- share/catkin
Multiple packages found with the same name "catkin_virtualenv":
- include/opt/ros/noetic/share/catkin_virtualenv
- share/catkin_virtualenv
Multiple packages found with the same name "class_loader":
- include/opt/ros/noetic/share/class_loader
- share/class_loader
Multiple packages found with the same name "cmake_modules":
- include/opt/ros/noetic/share/cmake_modules
- share/cmake_modules
Multiple packages found with the same name "common_msgs":
- include/opt/ros/noetic/share/common_msgs
- share/common_msgs
Multiple packages found with the same name "common_tutorials":
- include/opt/ros/noetic/share/common_tutorials
- share/common_tutorials
Multiple packages found with the same name "compressed_depth_image_transport":
- include/opt/ros/noetic/share/compressed_depth_image_transport
- share/compressed_depth_image_transport
Multiple packages found with the same name "compressed_image_transport":
- include/opt/ros/noetic/share/compressed_image_transport
- share/compressed_image_transport
Multiple packages found with the same name "control_msgs":
- include/opt/ros/noetic/share/control_msgs
- share/control_msgs
Multiple packages found with the same name "control_toolbox":
- include/opt/ros/noetic/share/control_toolbox
- share/control_toolbox
Multiple packages found with the same name "controller_interface":
- include/opt/ros/noetic/share/controller_interface
- share/controller_interface
Multiple packages found with the same name "controller_manager":
- include/opt/ros/noetic/share/controller_manager
- share/controller_manager
Multiple packages found with the same name "controller_manager_msgs":
- include/opt/ros/noetic/share/controller_manager_msgs
- share/controller_manager_msgs
Multiple packages found with the same name "costmap_2d":
- include/opt/ros/noetic/share/costmap_2d
- share/costmap_2d
Multiple packages found with the same name "cpp_common":
- include/opt/ros/noetic/share/cpp_common
- share/cpp_common
Multiple packages found with the same name "cv_bridge":
- include/opt/ros/noetic/share/cv_bridge
- share/cv_bridge
Multiple packages found with the same name "ddynamic_reconfigure":
- include/opt/ros/noetic/share/ddynamic_reconfigure
- share/ddynamic_reconfigure
Multiple packages found with the same name "depth_image_proc":
- include/opt/ros/noetic/share/depth_image_proc
- share/depth_image_proc
Multiple packages found with the same name "desktop":
- include/opt/ros/noetic/share/desktop
- share/desktop
Multiple packages found with the same name "desktop_full":
- include/opt/ros/noetic/share/desktop_full
- share/desktop_full
Multiple packages found with the same name "diagnostic_aggregator":
- include/opt/ros/noetic/share/diagnostic_aggregator
- share/diagnostic_aggregator
Multiple packages found with the same name "diagnostic_analysis":
- include/opt/ros/noetic/share/diagnostic_analysis
- share/diagnostic_analysis
Multiple packages found with the same name "diagnostic_common_diagnostics":
- include/opt/ros/noetic/share/diagnostic_common_diagnostics
- share/diagnostic_common_diagnostics
Multiple packages found with the same name "diagnostic_msgs":
- include/opt/ros/noetic/share/diagnostic_msgs
- share/diagnostic_msgs
Multiple packages found with the same name "diagnostic_updater":
- include/opt/ros/noetic/share/diagnostic_updater
- share/diagnostic_updater
Multiple packages found with the same name "diagnostics":
- include/opt/ros/noetic/share/diagnostics
- share/diagnostics
Multiple packages found with the same name "diff_drive_controller":
- include/opt/ros/noetic/share/diff_drive_controller
- share/diff_drive_controller
Multiple packages found with the same name "dynamic_reconfigure":
- include/opt/ros/noetic/share/dynamic_reconfigure
- share/dynamic_reconfigure
Multiple packages found with the same name "eigen_conversions":
- include/opt/ros/noetic/share/eigen_conversions
- share/eigen_conversions
Multiple packages found with the same name "executive_smach":
- include/opt/ros/noetic/share/executive_smach
- share/executive_smach
Multiple packages found with the same name "filters":
- include/opt/ros/noetic/share/filters
- share/filters
Multiple packages found with the same name "find_object_2d":
- include/opt/ros/noetic/share/find_object_2d
- share/find_object_2d
Multiple packages found with the same name "forward_command_controller":
- include/opt/ros/noetic/share/forward_command_controller
- share/forward_command_controller
Multiple packages found with the same name "gazebo_dev":
- include/opt/ros/noetic/share/gazebo_dev
- share/gazebo_dev
Multiple packages found with the same name "gazebo_msgs":
- include/opt/ros/noetic/share/gazebo_msgs
- share/gazebo_msgs
Multiple packages found with the same name "gazebo_plugins":
- include/opt/ros/noetic/share/gazebo_plugins
- share/gazebo_plugins
Multiple packages found with the same name "gazebo_ros":
- include/opt/ros/noetic/share/gazebo_ros
- share/gazebo_ros
Multiple packages found with the same name "gazebo_ros_control":
- include/opt/ros/noetic/share/gazebo_ros_control
- share/gazebo_ros_control
Multiple packages found with the same name "gazebo_ros_pkgs":
- include/opt/ros/noetic/share/gazebo_ros_pkgs
- share/gazebo_ros_pkgs
Multiple packages found with the same name "gencpp":
- include/opt/ros/noetic/share/gencpp
- share/gencpp
Multiple packages found with the same name "geneus":
- include/opt/ros/noetic/share/geneus
- share/geneus
Multiple packages found with the same name "genlisp":
- include/opt/ros/noetic/share/genlisp
- share/genlisp
Multiple packages found with the same name "genmsg":
- include/opt/ros/noetic/share/genmsg
- share/genmsg
Multiple packages found with the same name "gennodejs":
- include/opt/ros/noetic/share/gennodejs
- share/gennodejs
Multiple packages found with the same name "genpy":
- include/opt/ros/noetic/share/genpy
- share/genpy
Multiple packages found with the same name "geometry":
- include/opt/ros/noetic/share/geometry
- share/geometry
Multiple packages found with the same name "geometry_msgs":
- include/opt/ros/noetic/share/geometry_msgs
- share/geometry_msgs
Multiple packages found with the same name "geometry_tutorials":
- include/opt/ros/noetic/share/geometry_tutorials
- share/geometry_tutorials
Multiple packages found with the same name "gl_dependency":
- include/opt/ros/noetic/share/gl_dependency
- share/gl_dependency
Multiple packages found with the same name "hardware_interface":
- include/opt/ros/noetic/share/hardware_interface
- share/hardware_interface
Multiple packages found with the same name "image_common":
- include/opt/ros/noetic/share/image_common
- share/image_common
Multiple packages found with the same name "image_geometry":
- include/opt/ros/noetic/share/image_geometry
- share/image_geometry
Multiple packages found with the same name "image_pipeline":
- include/opt/ros/noetic/share/image_pipeline
- share/image_pipeline
Multiple packages found with the same name "image_proc":
- include/opt/ros/noetic/share/image_proc
- share/image_proc
Multiple packages found with the same name "image_publisher":
- include/opt/ros/noetic/share/image_publisher
- share/image_publisher
Multiple packages found with the same name "image_rotate":
- include/opt/ros/noetic/share/image_rotate
- share/image_rotate
Multiple packages found with the same name "image_transport":
- include/opt/ros/noetic/share/image_transport
- share/image_transport
Multiple packages found with the same name "image_transport_plugins":
- include/opt/ros/noetic/share/image_transport_plugins
- share/image_transport_plugins
Multiple packages found with the same name "image_view":
- include/opt/ros/noetic/share/image_view
- share/image_view
Multiple packages found with the same name "interactive_marker_tutorials":
- include/opt/ros/noetic/share/interactive_marker_tutorials
- share/interactive_marker_tutorials
Multiple packages found with the same name "interactive_markers":
- include/opt/ros/noetic/share/interactive_markers
- share/interactive_markers
Multiple packages found with the same name "joint_limits_interface":
- include/opt/ros/noetic/share/joint_limits_interface
- share/joint_limits_interface
Multiple packages found with the same name "joint_state_controller":
- include/opt/ros/noetic/share/joint_state_controller
- share/joint_state_controller
Multiple packages found with the same name "joint_state_publisher":
- include/opt/ros/noetic/share/joint_state_publisher
- share/joint_state_publisher
Multiple packages found with the same name "joint_state_publisher_gui":
- include/opt/ros/noetic/share/joint_state_publisher_gui
- share/joint_state_publisher_gui
Multiple packages found with the same name "kdl_conversions":
- include/opt/ros/noetic/share/kdl_conversions
- share/kdl_conversions
Multiple packages found with the same name "kdl_parser":
- include/opt/ros/noetic/share/kdl_parser
- share/kdl_parser
Multiple packages found with the same name "laser_assembler":
- include/opt/ros/noetic/share/laser_assembler
- share/laser_assembler
Multiple packages found with the same name "laser_filters":
- include/opt/ros/noetic/share/laser_filters
- share/laser_filters
Multiple packages found with the same name "laser_geometry":
- include/opt/ros/noetic/share/laser_geometry
- share/laser_geometry
Multiple packages found with the same name "laser_pipeline":
- include/opt/ros/noetic/share/laser_pipeline
- share/laser_pipeline
Multiple packages found with the same name "libg2o":
- include/opt/ros/noetic/share/libg2o
- share/libg2o
Multiple packages found with the same name "libnabo":
- include/opt/ros/noetic/share/libnabo
- share/libnabo
Multiple packages found with the same name "libpointmatcher":
- include/opt/ros/noetic/share/libpointmatcher
- share/libpointmatcher
Multiple packages found with the same name "librviz_tutorial":
- include/opt/ros/noetic/share/librviz_tutorial
- share/librviz_tutorial
Multiple packages found with the same name "map_msgs":
- include/opt/ros/noetic/share/map_msgs
- share/map_msgs
Multiple packages found with the same name "media_export":
- include/opt/ros/noetic/share/media_export
- share/media_export
Multiple packages found with the same name "message_filters":
- include/opt/ros/noetic/share/message_filters
- share/message_filters
Multiple packages found with the same name "message_generation":
- include/opt/ros/noetic/share/message_generation
- share/message_generation
Multiple packages found with the same name "message_runtime":
- include/opt/ros/noetic/share/message_runtime
- share/message_runtime
Multiple packages found with the same name "mk":
- include/opt/ros/noetic/share/mk
- share/mk
Multiple packages found with the same name "move_base_msgs":
- include/opt/ros/noetic/share/move_base_msgs
- share/move_base_msgs
Multiple packages found with the same name "nav_msgs":
- include/opt/ros/noetic/share/nav_msgs
- share/nav_msgs
Multiple packages found with the same name "nmea_msgs":
- include/opt/ros/noetic/share/nmea_msgs
- share/nmea_msgs
Multiple packages found with the same name "nodelet":
- include/opt/ros/noetic/share/nodelet
- share/nodelet
Multiple packages found with the same name "nodelet_core":
- include/opt/ros/noetic/share/nodelet_core
- share/nodelet_core
Multiple packages found with the same name "nodelet_topic_tools":
- include/opt/ros/noetic/share/nodelet_topic_tools
- share/nodelet_topic_tools
Multiple packages found with the same name "nodelet_tutorial_math":
- include/opt/ros/noetic/share/nodelet_tutorial_math
- share/nodelet_tutorial_math
Multiple packages found with the same name "octomap":
- include/opt/ros/noetic/share/octomap
- share/octomap
Multiple packages found with the same name "octomap_msgs":
- include/opt/ros/noetic/share/octomap_msgs
- share/octomap_msgs
Multiple packages found with the same name "octomap_ros":
- include/opt/ros/noetic/share/octomap_ros
- share/octomap_ros
Multiple packages found with the same name "octomap_rviz_plugins":
- include/opt/ros/noetic/share/octomap_rviz_plugins
- share/octomap_rviz_plugins
Multiple packages found with the same name "pcl_conversions":
- include/opt/ros/noetic/share/pcl_conversions
- share/pcl_conversions
Multiple packages found with the same name "pcl_msgs":
- include/opt/ros/noetic/share/pcl_msgs
- share/pcl_msgs
Multiple packages found with the same name "pcl_ros":
- include/opt/ros/noetic/share/pcl_ros
- share/pcl_ros
Multiple packages found with the same name "perception":
- include/opt/ros/noetic/share/perception
- share/perception
Multiple packages found with the same name "perception_pcl":
- include/opt/ros/noetic/share/perception_pcl
- share/perception_pcl
Multiple packages found with the same name "pluginlib":
- include/opt/ros/noetic/share/pluginlib
- share/pluginlib
Multiple packages found with the same name "pluginlib_tutorials":
- include/opt/ros/noetic/share/pluginlib_tutorials
- share/pluginlib_tutorials
Multiple packages found with the same name "polled_camera":
- include/opt/ros/noetic/share/polled_camera
- share/polled_camera
Multiple packages found with the same name "position_controllers":
- include/opt/ros/noetic/share/position_controllers
- share/position_controllers
Multiple packages found with the same name "python_qt_binding":
- include/opt/ros/noetic/share/python_qt_binding
- share/python_qt_binding
Multiple packages found with the same name "qt_dotgraph":
- include/opt/ros/noetic/share/qt_dotgraph
- share/qt_dotgraph
Multiple packages found with the same name "qt_gui":
- include/opt/ros/noetic/share/qt_gui
- share/qt_gui
Multiple packages found with the same name "qt_gui_cpp":
- include/opt/ros/noetic/share/qt_gui_cpp
- share/qt_gui_cpp
Multiple packages found with the same name "qt_gui_py_common":
- include/opt/ros/noetic/share/qt_gui_py_common
- share/qt_gui_py_common
Multiple packages found with the same name "qwt_dependency":
- include/opt/ros/noetic/share/qwt_dependency
- share/qwt_dependency
Multiple packages found with the same name "realtime_tools":
- include/opt/ros/noetic/share/realtime_tools
- share/realtime_tools
Multiple packages found with the same name "resource_retriever":
- include/opt/ros/noetic/share/resource_retriever
- share/resource_retriever
Multiple packages found with the same name "robot":
- include/opt/ros/noetic/share/robot
- share/robot
Multiple packages found with the same name "robot_state_publisher":
- include/opt/ros/noetic/share/robot_state_publisher
- share/robot_state_publisher
Multiple packages found with the same name "ros":
- include/opt/ros/noetic/share/ros
- share/ros
Multiple packages found with the same name "ros_base":
- include/opt/ros/noetic/share/ros_base
- share/ros_base
Multiple packages found with the same name "ros_comm":
- include/opt/ros/noetic/share/ros_comm
- share/ros_comm
Multiple packages found with the same name "ros_core":
- include/opt/ros/noetic/share/ros_core
- share/ros_core
Multiple packages found with the same name "ros_environment":
- include/opt/ros/noetic/share/ros_environment
- share/ros_environment
Multiple packages found with the same name "ros_tutorials":
- include/opt/ros/noetic/share/ros_tutorials
- share/ros_tutorials
Multiple packages found with the same name "rosbag":
- include/opt/ros/noetic/share/rosbag
- share/rosbag
Multiple packages found with the same name "rosbag_migration_rule":
- include/opt/ros/noetic/share/rosbag_migration_rule
- share/rosbag_migration_rule
Multiple packages found with the same name "rosbag_storage":
- include/opt/ros/noetic/share/rosbag_storage
- share/rosbag_storage
Multiple packages found with the same name "rosbash":
- include/opt/ros/noetic/share/rosbash
- share/rosbash
Multiple packages found with the same name "rosboost_cfg":
- include/opt/ros/noetic/share/rosboost_cfg
- share/rosboost_cfg
Multiple packages found with the same name "rosbuild":
- include/opt/ros/noetic/share/rosbuild
- share/rosbuild
Multiple packages found with the same name "rosclean":
- include/opt/ros/noetic/share/rosclean
- share/rosclean
Multiple packages found with the same name "rosconsole":
- include/opt/ros/noetic/share/rosconsole
- share/rosconsole
Multiple packages found with the same name "rosconsole_bridge":
- include/opt/ros/noetic/share/rosconsole_bridge
- share/rosconsole_bridge
Multiple packages found with the same name "roscpp":
- include/opt/ros/noetic/share/roscpp
- share/roscpp
Multiple packages found with the same name "roscpp_core":
- include/opt/ros/noetic/share/roscpp_core
- share/roscpp_core
Multiple packages found with the same name "roscpp_serialization":
- include/opt/ros/noetic/share/roscpp_serialization
- share/roscpp_serialization
Multiple packages found with the same name "roscpp_traits":
- include/opt/ros/noetic/share/roscpp_traits
- share/roscpp_traits
Multiple packages found with the same name "roscpp_tutorials":
- include/opt/ros/noetic/share/roscpp_tutorials
- share/roscpp_tutorials
Multiple packages found with the same name "roscreate":
- include/opt/ros/noetic/share/roscreate
- share/roscreate
Multiple packages found with the same name "rosgraph":
- include/opt/ros/noetic/share/rosgraph
- share/rosgraph
Multiple packages found with the same name "rosgraph_msgs":
- include/opt/ros/noetic/share/rosgraph_msgs
- share/rosgraph_msgs
Multiple packages found with the same name "roslang":
- include/opt/ros/noetic/share/roslang
- share/roslang
Multiple packages found with the same name "roslaunch":
- include/opt/ros/noetic/share/roslaunch
- share/roslaunch
Multiple packages found with the same name "roslib":
- include/opt/ros/noetic/share/roslib
- share/roslib
Multiple packages found with the same name "roslint":
- include/opt/ros/noetic/share/roslint
- share/roslint
Multiple packages found with the same name "roslisp":
- include/opt/ros/noetic/share/roslisp
- share/roslisp
Multiple packages found with the same name "roslz4":
- include/opt/ros/noetic/share/roslz4
- share/roslz4
Multiple packages found with the same name "rosmake":
- include/opt/ros/noetic/share/rosmake
- share/rosmake
Multiple packages found with the same name "rosmaster":
- include/opt/ros/noetic/share/rosmaster
- share/rosmaster
Multiple packages found with the same name "rosmsg":
- include/opt/ros/noetic/share/rosmsg
- share/rosmsg
Multiple packages found with the same name "rosnode":
- include/opt/ros/noetic/share/rosnode
- share/rosnode
Multiple packages found with the same name "rosout":
- include/opt/ros/noetic/share/rosout
- share/rosout
Multiple packages found with the same name "rospack":
- include/opt/ros/noetic/share/rospack
- share/rospack
Multiple packages found with the same name "rosparam":
- include/opt/ros/noetic/share/rosparam
- share/rosparam
Multiple packages found with the same name "rospy":
- include/opt/ros/noetic/share/rospy
- share/rospy
Multiple packages found with the same name "rospy_tutorials":
- include/opt/ros/noetic/share/rospy_tutorials
- share/rospy_tutorials
Multiple packages found with the same name "rosservice":
- include/opt/ros/noetic/share/rosservice
- share/rosservice
Multiple packages found with the same name "rostest":
- include/opt/ros/noetic/share/rostest
- share/rostest
Multiple packages found with the same name "rostime":
- include/opt/ros/noetic/share/rostime
- share/rostime
Multiple packages found with the same name "rostopic":
- include/opt/ros/noetic/share/rostopic
- share/rostopic
Multiple packages found with the same name "rosunit":
- include/opt/ros/noetic/share/rosunit
- share/rosunit
Multiple packages found with the same name "roswtf":
- include/opt/ros/noetic/share/roswtf
- share/roswtf
Multiple packages found with the same name "rqt_action":
- include/opt/ros/noetic/share/rqt_action
- share/rqt_action
Multiple packages found with the same name "rqt_bag":
- include/opt/ros/noetic/share/rqt_bag
- share/rqt_bag
Multiple packages found with the same name "rqt_bag_plugins":
- include/opt/ros/noetic/share/rqt_bag_plugins
- share/rqt_bag_plugins
Multiple packages found with the same name "rqt_common_plugins":
- include/opt/ros/noetic/share/rqt_common_plugins
- share/rqt_common_plugins
Multiple packages found with the same name "rqt_console":
- include/opt/ros/noetic/share/rqt_console
- share/rqt_console
Multiple packages found with the same name "rqt_dep":
- include/opt/ros/noetic/share/rqt_dep
- share/rqt_dep
Multiple packages found with the same name "rqt_graph":
- include/opt/ros/noetic/share/rqt_graph
- share/rqt_graph
Multiple packages found with the same name "rqt_gui":
- include/opt/ros/noetic/share/rqt_gui
- share/rqt_gui
Multiple packages found with the same name "rqt_gui_cpp":
- include/opt/ros/noetic/share/rqt_gui_cpp
- share/rqt_gui_cpp
Multiple packages found with the same name "rqt_gui_py":
- include/opt/ros/noetic/share/rqt_gui_py
- share/rqt_gui_py
Multiple packages found with the same name "rqt_image_view":
- include/opt/ros/noetic/share/rqt_image_view
- share/rqt_image_view
Multiple packages found with the same name "rqt_launch":
- include/opt/ros/noetic/share/rqt_launch
- share/rqt_launch
Multiple packages found with the same name "rqt_logger_level":
- include/opt/ros/noetic/share/rqt_logger_level
- share/rqt_logger_level
Multiple packages found with the same name "rqt_moveit":
- include/opt/ros/noetic/share/rqt_moveit
- share/rqt_moveit
Multiple packages found with the same name "rqt_msg":
- include/opt/ros/noetic/share/rqt_msg
- share/rqt_msg
Multiple packages found with the same name "rqt_nav_view":
- include/opt/ros/noetic/share/rqt_nav_view
- share/rqt_nav_view
Multiple packages found with the same name "rqt_plot":
- include/opt/ros/noetic/share/rqt_plot
- share/rqt_plot
Multiple packages found with the same name "rqt_pose_view":
- include/opt/ros/noetic/share/rqt_pose_view
- share/rqt_pose_view
Multiple packages found with the same name "rqt_publisher":
- include/opt/ros/noetic/share/rqt_publisher
- share/rqt_publisher
Multiple packages found with the same name "rqt_py_common":
- include/opt/ros/noetic/share/rqt_py_common
- share/rqt_py_common
Multiple packages found with the same name "rqt_py_console":
- include/opt/ros/noetic/share/rqt_py_console
- share/rqt_py_console
Multiple packages found with the same name "rqt_reconfigure":
- include/opt/ros/noetic/share/rqt_reconfigure
- share/rqt_reconfigure
Multiple packages found with the same name "rqt_robot_dashboard":
- include/opt/ros/noetic/share/rqt_robot_dashboard
- share/rqt_robot_dashboard
Multiple packages found with the same name "rqt_robot_monitor":
- include/opt/ros/noetic/share/rqt_robot_monitor
- share/rqt_robot_monitor
Multiple packages found with the same name "rqt_robot_plugins":
- include/opt/ros/noetic/share/rqt_robot_plugins
- share/rqt_robot_plugins
Multiple packages found with the same name "rqt_robot_steering":
- include/opt/ros/noetic/share/rqt_robot_steering
- share/rqt_robot_steering
Multiple packages found with the same name "rqt_runtime_monitor":
- include/opt/ros/noetic/share/rqt_runtime_monitor
- share/rqt_runtime_monitor
Multiple packages found with the same name "rqt_rviz":
- include/opt/ros/noetic/share/rqt_rviz
- share/rqt_rviz
Multiple packages found with the same name "rqt_service_caller":
- include/opt/ros/noetic/share/rqt_service_caller
- share/rqt_service_caller
Multiple packages found with the same name "rqt_shell":
- include/opt/ros/noetic/share/rqt_shell
- share/rqt_shell
Multiple packages found with the same name "rqt_srv":
- include/opt/ros/noetic/share/rqt_srv
- share/rqt_srv
Multiple packages found with the same name "rqt_tf_tree":
- include/opt/ros/noetic/share/rqt_tf_tree
- share/rqt_tf_tree
Multiple packages found with the same name "rqt_top":
- include/opt/ros/noetic/share/rqt_top
- share/rqt_top
Multiple packages found with the same name "rqt_topic":
- include/opt/ros/noetic/share/rqt_topic
- share/rqt_topic
Multiple packages found with the same name "rqt_web":
- include/opt/ros/noetic/share/rqt_web
- share/rqt_web
Multiple packages found with the same name "rtabmap":
- include/opt/ros/noetic/share/rtabmap
- share/rtabmap
Multiple packages found with the same name "rviz":
- include/opt/ros/noetic/share/rviz
- share/rviz
Multiple packages found with the same name "rviz_plugin_tutorials":
- include/opt/ros/noetic/share/rviz_plugin_tutorials
- share/rviz_plugin_tutorials
Multiple packages found with the same name "rviz_python_tutorial":
- include/opt/ros/noetic/share/rviz_python_tutorial
- share/rviz_python_tutorial
Multiple packages found with the same name "self_test":
- include/opt/ros/noetic/share/self_test
- share/self_test
Multiple packages found with the same name "sensor_msgs":
- include/opt/ros/noetic/share/sensor_msgs
- share/sensor_msgs
Multiple packages found with the same name "serial":
- include/opt/ros/noetic/share/serial
- share/serial
Multiple packages found with the same name "shape_msgs":
- include/opt/ros/noetic/share/shape_msgs
- share/shape_msgs
Multiple packages found with the same name "simulators":
- include/opt/ros/noetic/share/simulators
- share/simulators
Multiple packages found with the same name "smach":
- include/opt/ros/noetic/share/smach
- share/smach
Multiple packages found with the same name "smach_msgs":
- include/opt/ros/noetic/share/smach_msgs
- share/smach_msgs
Multiple packages found with the same name "smach_ros":
- include/opt/ros/noetic/share/smach_ros
- share/smach_ros
Multiple packages found with the same name "smclib":
- include/opt/ros/noetic/share/smclib
- share/smclib
Multiple packages found with the same name "stage":
- include/opt/ros/noetic/share/stage
- share/stage
Multiple packages found with the same name "stage_ros":
- include/opt/ros/noetic/share/stage_ros
- share/stage_ros
Multiple packages found with the same name "std_msgs":
- include/opt/ros/noetic/share/std_msgs
- share/std_msgs
Multiple packages found with the same name "std_srvs":
- include/opt/ros/noetic/share/std_srvs
- share/std_srvs
Multiple packages found with the same name "stereo_image_proc":
- include/opt/ros/noetic/share/stereo_image_proc
- share/stereo_image_proc
Multiple packages found with the same name "stereo_msgs":
- include/opt/ros/noetic/share/stereo_msgs
- share/stereo_msgs
Multiple packages found with the same name "tf":
- include/opt/ros/noetic/share/tf
- share/tf
Multiple packages found with the same name "tf2":
- include/opt/ros/noetic/share/tf2
- share/tf2
Multiple packages found with the same name "tf2_eigen":
- include/opt/ros/noetic/share/tf2_eigen
- share/tf2_eigen
Multiple packages found with the same name "tf2_geometry_msgs":
- include/opt/ros/noetic/share/tf2_geometry_msgs
- share/tf2_geometry_msgs
Multiple packages found with the same name "tf2_kdl":
- include/opt/ros/noetic/share/tf2_kdl
- share/tf2_kdl
Multiple packages found with the same name "tf2_msgs":
- include/opt/ros/noetic/share/tf2_msgs
- share/tf2_msgs
Multiple packages found with the same name "tf2_py":
- include/opt/ros/noetic/share/tf2_py
- share/tf2_py
Multiple packages found with the same name "tf2_ros":
- include/opt/ros/noetic/share/tf2_ros
- share/tf2_ros
Multiple packages found with the same name "tf_conversions":
- include/opt/ros/noetic/share/tf_conversions
- share/tf_conversions
Multiple packages found with the same name "theora_image_transport":
- include/opt/ros/noetic/share/theora_image_transport
- share/theora_image_transport
Multiple packages found with the same name "topic_tools":
- include/opt/ros/noetic/share/topic_tools
- share/topic_tools
Multiple packages found with the same name "trajectory_msgs":
- include/opt/ros/noetic/share/trajectory_msgs
- share/trajectory_msgs
Multiple packages found with the same name "transmission_interface":
- include/opt/ros/noetic/share/transmission_interface
- share/transmission_interface
Multiple packages found with the same name "turtle_actionlib":
- include/opt/ros/noetic/share/turtle_actionlib
- share/turtle_actionlib
Multiple packages found with the same name "turtle_tf":
- include/opt/ros/noetic/share/turtle_tf
- share/turtle_tf
Multiple packages found with the same name "turtle_tf2":
- include/opt/ros/noetic/share/turtle_tf2
- share/turtle_tf2
Multiple packages found with the same name "turtlesim":
- include/opt/ros/noetic/share/turtlesim
- share/turtlesim
Multiple packages found with the same name "urdf":
- include/opt/ros/noetic/share/urdf
- share/urdf
Multiple packages found with the same name "urdf_parser_plugin":
- include/opt/ros/noetic/share/urdf_parser_plugin
- share/urdf_parser_plugin
Multiple packages found with the same name "urdf_sim_tutorial":
- include/opt/ros/noetic/share/urdf_sim_tutorial
- share/urdf_sim_tutorial
Multiple packages found with the same name "urdf_tutorial":
- include/opt/ros/noetic/share/urdf_tutorial
- share/urdf_tutorial
Multiple packages found with the same name "vision_opencv":
- include/opt/ros/noetic/share/vision_opencv
- share/vision_opencv
Multiple packages found with the same name "visualization_marker_tutorials":
- include/opt/ros/noetic/share/visualization_marker_tutorials
- share/visualization_marker_tutorials
Multiple packages found with the same name "visualization_msgs":
- include/opt/ros/noetic/share/visualization_msgs
- share/visualization_msgs
Multiple packages found with the same name "visualization_tutorials":
- include/opt/ros/noetic/share/visualization_tutorials
- share/visualization_tutorials
Multiple packages found with the same name "viz":
- include/opt/ros/noetic/share/viz
- share/viz
Multiple packages found with the same name "voxel_grid":
- include/opt/ros/noetic/share/voxel_grid
- share/voxel_grid
Multiple packages found with the same name "webkit_dependency":
- include/opt/ros/noetic/share/webkit_dependency
- share/webkit_dependency
Multiple packages found with the same name "xacro":
- include/opt/ros/noetic/share/xacro
- share/xacro
Multiple packages found with the same name "xmlrpcpp":
- include/opt/ros/noetic/share/xmlrpcpp
- share/xmlrpcpp
make[2]: *** [CMakeFiles/zivid_camera_generate_messages_eus.dir/build.make:81: /home/erp42/catkin_ws/devel/.private/zivid_camera/share/roseus/ros/zivid_camera/manifest.l] Error 3
make[1]: *** [CMakeFiles/Makefile2:1796: CMakeFiles/zivid_camera_generate_messages_eus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:146: all] Error 2
cd /home/erp42/catkin_ws/build/zivid_camera; catkin build --get-env zivid_camera | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

...............................................................................
Failed     << zivid_camera:make            [ Exited with code 2 ]              
Failed    <<< zivid_camera                 [ 0.6 seconds ]                     
Abandoned <<< zivid_samples                [ Unrelated job failed ]            
[build] Summary: 0 of 2 packages succeeded.                                    
[build]   Ignored:   23 packages were skipped or are skiplisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: 1 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.7 seconds total.

**Comment by apartridge** [comment]
Hi. You have many variants of this error for many packages:
```
RuntimeError: Multiple packages found with the same name "actionlib":

include/opt/ros/noetic/share/actionlib
share/actionlib
```
So it appears it finds multiple packages with the same names in your workspace.
I haven't seen your error before, but I see several results when googling for "Multiple packages found with the same name".
Can you check if any of these are applicable for you?

We do build our driver with ros-noetic in our CI and do works (but sometimes tests fails for different reason). So it should work to build our driver from a clean machine & workspace.

**Comment by apartridge** [comment]
Closing this issue due to no response from reporter, and since we have now moved to ROS2.
