### ISSUE TITLE
Intrinsic parameters

### ISSUE THREAD

**Issue by TedMorell** [zivid/zivid-ros#77]
Hi all,

I am working on a Zivid One + S 3D camera.
I was wondering if the camera_info data was relying on default parameters (used by ROS) or if the intrinsic parameters of the camera that were factory calibrated and read by Ros.
Also, I am trying to do full calibration of this camera but I cannot find the pixel size information (in micrometers).
Any suggestions welcome.

Thanks in advance,
Ted

**Comment by SatjaSivcev** [comment]
Hi, it is the camera intrinsics read from the camera; the hard-coded ones, not the ones estimated from the point cloud.

Pixel size:
- One+: 5.86 um
- Two: 4.5 um

I am interested to hear more about your motivation to calibrate the camera, as it is already calibrated.
However, I think it is best if you reach out to us via customersuccess@zivid.com so we can discuss the topic.
